version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails

  pgloader:
    image: dimitri/pgloader
    depends_on:
      - postgres
    working_dir: /var/src
    volumes:
      - .:/var/src:ro
    command: bash pgloader.sh
