version: '3'

networks:
  www:
    external:
      name: www

volumes:
  vendor_bundle:

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
    # restart: unless-stopped

  rails:
    image: ruby:2.7.1
    depends_on:
      - postgres
    env_file:
      - .secrets.env
    working_dir: /var/src
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
    volumes:
      - .:/var/src:ro
      - ./Gemfile.lock:/var/src/Gemfile.lock:delegated
      - ./db:/var/src/db:delegated
      - ./log:/var/src/log:delegated
      - ./tmp:/var/src/tmp:delegated
      - vendor_bundle:/usr/local/bundle
      - ./public/assets:/var/src/public/assets:delegated
    entrypoint: /var/src/entrypoint.sh
    command: rails server
    # restart: unless-stopped

  nginx:
    image: nginx
    depends_on:
      - rails
    env_file:
      - .web.env
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    networks:
      - default
      - www
    # restart: unless-stopped
