default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'rails' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'rails' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'postgres' } %>
  port: 5432

development:
  <<: *default
  database: dckhri970jog8

test:
  <<: *default
  database: calendarlog_test

production:
  <<: *default
  database: calendarlog_production
